### ISSUE TITLE
numpy 1.13.0 and tensorflow 1.8.0

### ISSUE THREAD

**Issue by derethor** [MycroftAI/mimic2#13]
Hello!

I tried to build the cpu version with docker

and I got this message: 

tensorflow 1.8.0 has requirement numpy>=1.13.3, but you'll have numpy 1.13.0 which is incompatible.

I see that the requirement.txt has 1.13.0 version... is this for any particular reason?

**Comment by LearnedVector** [comment]
@derethor is this preventing mimic2 from working? it seems that it still is working in my case
