### ISSUE TITLE
Docker file not found

### ISSUE THREAD

**Issue by Vino-git** [MycroftAI/mimic2#14]
Hi, After the CPU docker build done successfully. 

successful confirmation,
vinoth@vinoth-Acer:~/mimic2$ docker run -it -p 3000:3000 mycroft/mimic2:cpu
Unable to find image 'mycroft/mimic2:cpu' locally

docker run -it -p 3000:3000 mycroft/mimic2:cpu

docker run -it -p 3000:3000 mycroft/mimic2:cpu
Unable to find image 'mycroft/mimic2:cpu' locally

**Comment by LearnedVector** [comment]
hello, i had a typo in my doc to build the cpu with the :gpu tag at the end. if you do docker images, it might have built it as mycroft/mimic2:gpu instead of mycroft/mimic2:cpu. the error is fixed in the README now
