### ISSUE TITLE
demo_server.py throwing error when generating response

### ISSUE THREAD

**Issue by el-tocino** [MycroftAI/mimic2#19]
ubuntu 17.04.  git pull on 9.25 indicates I am up to date with master branch.  

Running:
```
python3 demo_server.py --checkpoint ~/tmp/model.ckpt-50000
```
starts as expected. I am able to navigate to the page, and type in a sample to have it generate ("this is a test").  After what would be the time expected to return a result, I get the following in the demo_server log/console output: 

```
127.0.0.1 - - [24/Sep/2018 18:50:07] "GET /synthesize?text=this%20is%20a%20test HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 260, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 944, in __next__
    data = self.file.read(self.buffer_size)
AttributeError: 'bytes' object has no attribute 'read'
```
I googled that and it looked more like a urllib3 error, however I'm not able to discern why it's happening here.  

Thanks!

ETA....
I pulled a fresh install onto a different system, same issue.

**Comment by el-tocino** [comment]
Also getting an issue running eval.py:
Synthesizing and plotting: /home/test/tmp/eval-74000-0.wav
Traceback (most recent call last):
  File "eval.py", line 88, in <module>
    main()
  File "eval.py", line 84, in main
    run_eval(args)
  File "eval.py", line 53, in run_eval
    f.write(wav.getvalue())
AttributeError: 'bytes' object has no attribute 'getvalue

**Comment by el-tocino** [comment]
Any ideas?  I'm curious to test a model under the updated format.

**Comment by LearnedVector** [comment]
looks like you fixed it! thanks! https://github.com/MycroftAI/mimic2/pull/21
