### ISSUE TITLE
Illegal instruction (core dumped) on preprocessor

### ISSUE THREAD

**Issue by Simonmicro** [MycroftAI/mimic2#31]
Issue:
Well, I've got the error `Illegal instruction (core dumped)` at executing `python3 preprocess.py --dataset ljspeech` inside the docker image from the master branch.
Any idea? I mean: This should not happen because the docker container is an independent system...

Workaround:
Use tensorflow version 1.5 and compile ffmpeg for yourself to provide the missing avconv (how to see [there](https://superuser.com/questions/286675/how-to-install-ffmpeg-on-debian))

**Comment by el-tocino** [comment]
There's a few issues possibly related about this, usually due to Tensorflow being compiled expecting AVX and other hardware instructions (on x86).  On linux, you can do ```grep avx /proc/cpuinfo```.  There's a couple solutions, compile yourself or find a wheel of tensorflow that's been compiled without it.

**Comment by Simonmicro** [comment]
And my main pcs cpu doesn't have this extension - damn! And not even my server! Well, I guess my workaround has simply to do the work :smile:
