### ISSUE TITLE
Pronunciation might depend on word order

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/mimic2#39]
I've been experimenting with the American male voice, and I've noticed a couple of instances where word order affects pronunciation.

First of all, it can pronounce the word "code," but when I asked it to say, "arbitrary code," it talked about arbitrary _cod_.

Also, "Oregon." I tried to nail down the correct pronunciation, and found that:

"Ora-ggn" sounds right, and "Ora-ggn State" sounds best, but "State of Ora-ggn" catches on the second syllable.

However, "Ora-gnn" sounds _okay_, "Ora-gnn State" sounds all wrong, and "State of Ora-gnn" sounds just right!

**Comment by el-tocino** [comment]
The models aren't built on individual words (for the most part) so they look at the structure of the sentence to generate the results. You're finding the results of how that can change things.  

On local instances, it may help to add a comma or period into the request in spots, or even alter the spelling of certain words you want it to say.

**Comment by ChanceNCounter** [comment]
I should probably close this, but it might be helpful to start assembling common solutions someplace. "Tips for writing dialog" or something.
